name: Composer and test

on:
  pull_request: # on PR creation and update
  push:
    branches:
      - develop # triggers on PR merge
    tags:
      - '*' # on new tags 
  workflow_dispatch: # manual




jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: pecl

      - name: Cache Composer packages
        id: composer-cache-target
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Test install dependencies
        run: composer install --no-progress
        
      - name: Run server and tests
        env:
          apiSecretKey: ${{ secrets.APISECRETKEY }}
          apiPublicKey: ${{ secrets.APIPUBLICKEY }}
          checkoutEndpointSecret: ${{ secrets.CHECKOUTENDPOINTSECRET }}
          subscriptionEndpointSecret: ${{ secrets.SUBSCRIPTIONENDPOINTSECRET }}
          priceId: ${{ secrets.PRICEID }}
          checkoutReturnUrl: "http://127.0.0.1:4242/?route: returnPage&sessionId: {CHECKOUT_SESSION_ID}"
          portalReturnUrl: http://127.0.0.1:4242/
          # email or id
          customerIdMode: email
          customerEmail: ${{ secrets.CUSTOMEREMAIL }}
          customerId: ${{ secrets.CUSTOMERID }}
        shell: bash
        run: |
          docker run -d -e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1080 -e SCREEN_DEPTH=24 --shm-size="2g" --net=host --add-host=host.docker.internal:host-gateway selenium/standalone-chrome:latest
          sleep 5
          cd demo-app 
          composer install --no-progress
          php -d variables_order=EGPCS -S 0.0.0.0:4242 --docroot=web & 
          cd .. 
          ./vendor/bin/phpunit tests

      - name: Upload failure screenshots if appropriate
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: selenium_screenshots
          path: /tmp/*.png